project:
  type: website
  output-dir: "out"

date-format: iso
theme:
  # https://quarto.org/docs/output-formats/html-themes.html
  light: yeti
  dark: superhero

website:
  title: "About me - uma-chan"
  site-url: "https://i9wa4.github.io/about"
