project:
  type: website
  output-dir: "docs"

date-format: iso
theme:
  light: flatly
  dark: darkly

website:
  title: "i9wa4's page"
  site-url: "https://i9wa4.github.io/"
  favicon: "/assets/icon_hhkb2.jpg"
  image: "/assets/icon_hhkb2.jpg"
  search: false
  twitter-card:
    card-style: summary
    creator: "@i9wa4_"
    site: "@i9wa4_"
  open-graph: true
