name: Render Quarto Project and Deploy to branch internal
run-name: ${{ github.event_name }} on ${{ github.ref_name }} by @${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches: main
permissions: {}
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}  # 同一PRでの多重起動を抑制する
  cancel-in-progress: true  # 既存の実行をキャンセルして新しい実行を開始させる

jobs:
  render:
    runs-on: ubuntu-24.04-arm64
    permissions:
      contents: write
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render
        uses: quarto-dev/quarto-actions/render@v2
      - name: Deploy to internal branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Specify the directory where Quarto renders the output
          # The default output directory for Quarto projects is usually _site
          publish_dir: ./_site
          # Specify the branch name to deploy to
          publish_branch: internal
          # Optional: Set a commit message
          commit_message: 'Deploy rendered Quarto project to internal branch'
          # Optional: Set the user name and email for the commit
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
